data:extend(
{
   {
    type = "fluid",
    name = "dream-concentrate",
    icon = "__cubium__/graphics/icons/fluid/dream-concentrate.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {30/256,10/256,30/256},--TODO
    flow_color = {0.22, 0.4, 1.35},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "emotional-tar",
    icon = "__cubium__/graphics/icons/fluid/emotional-tar.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {0, 0, 0},
    flow_color = {0.5, 0.5, 0.5},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "liquid-anger",
    icon = "__cubium__/graphics/icons/fluid/liquid-anger.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {1, 0.13, 0},
    flow_color = {1.4, 0.6, 0.3},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "ultradense-lava",
    icon = "__cubium__/graphics/icons/fluid/ultradense-lava.png",
    subgroup = "fluid",
    --order = "b[new-fluid]-b[cubium]-a[ultradense]",
    default_temperature = 1500,
    max_temperature = 2000,
    heat_capacity = "1kJ",
    base_color = {0.1, 0.4, 1}, 
    flow_color = {0, 0.1, 0.3},
    auto_barrel = false
   },
   {
    type = "fluid",
    name = "liquid-courage",
    icon = "__cubium__/graphics/icons/fluid/liquid-courage.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {0.1, 0.4, 1}, 
    flow_color = {0, 0.1, 0.3},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "liquid-disgust",
    icon = "__cubium__/graphics/icons/fluid/liquid-disgust.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {0.1, 1, 0.4}, 
    flow_color = {0, 0.3, 0.1},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "liquid-dream",
    icon = "__cubium__/graphics/icons/fluid/liquid-dream.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {0.5, 0.13, 0},
    flow_color = {0.7, 0.2, 0.2},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "liquid-fear",
    icon = "__cubium__/graphics/icons/fluid/liquid-dream.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {0.57, 0.33, 0},
    flow_color = {1, 0.73, 0.07},
    auto_barrel = true,
   },
   {
    type = "fluid",
    name = "liquid-hope",
    icon = "__cubium__/graphics/icons/fluid/liquid-hope.png",
    subgroup = "fluid",
    default_temperature = 21,
    max_temperature = 200,
    heat_capacity = "4.184kJ",
    base_color = {1, 0.4, 1}, 
    flow_color = {0.3, 0.1, 0.3},
    auto_barrel = true,
   },
   {
      type = "fluid",
      name = "liquid-hate",
      icon = "__cubium__/graphics/icons/fluid/liquid-hate.png",
      subgroup = "fluid",
      default_temperature = 21,
      max_temperature = 200,
      heat_capacity = "4.184kJ",
      base_color = {0.5, 0.13, 0},
      flow_color = {0.85, 0.6, 0.3},
      auto_barrel = true,
   },


})